"""Layout components.

`Container` predates WS-16 (hand-written). `Column`, `Footer`, `Hero`,
`Level`, `Media`, `Section`, `Shell`, `Tile`, `Title` are generated by
`scripts/generate_components.py` from fastblocks-ui's manifest
(`fastblocks_htmy/layout/_generated.py` -- do not edit that file by hand).
`Columns`, `NavList` and `NavGroups` are hand-written carve-outs (see each
module's docstring for why). `Shell`, `NavList` and `NavGroups` arrived with
fastblocks-ui 0.8.0.
"""

from __future__ import annotations

from ._generated import (
    Column,
    Footer,
    Hero,
    Level,
    Media,
    Section,
    Shell,
    Tile,
    Title,
)
from .columns import Columns
from .container import Container
from .nav_groups import NavGroups
from .nav_list import NavList

__all__ = [
    "Shell",
    "Column",
    "Columns",
    "Container",
    "NavGroups",
    "NavList",
    "Footer",
    "Hero",
    "Level",
    "Media",
    "Section",
    "Tile",
    "Title",
]
