"""AUTOGENERATED by scripts/generate_components.py -- DO NOT EDIT BY HAND.

Regenerate with:
    python scripts/generate_components.py

Source of truth: fastblocks-ui's manifest.json `params` (itself derived from
the real `fastblocks_ui.helpers` signatures by fastblocks-ui's own
scripts/sync_manifest_params.py). Any manual edit here will be overwritten the
next time this script runs.
"""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any

from fastblocks_ui import HeadingLevel, Size, Variant
from fastblocks_ui import (
    column as _column,
)
from fastblocks_ui import (
    footer as _footer,
)
from fastblocks_ui import (
    hero as _hero,
)
from fastblocks_ui import (
    level as _level,
)
from fastblocks_ui import (
    media as _media,
)
from fastblocks_ui import (
    section as _section,
)
from fastblocks_ui import (
    shell as _shell,
)
from fastblocks_ui import (
    tile as _tile,
)
from fastblocks_ui import (
    title as _title,
)
from htmy import Context

from ..base import FastBlocksComponent


@dataclass
class Column(FastBlocksComponent):
    """Individual column within a columns grid.

    Thin wrapper over :func:`fastblocks_ui.column`; emits identical markup.
    """

    content: object = None
    size: str | None = None
    offset: str | None = None
    narrow: bool = False
    full: bool = False
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _column(
                content=self.content,
                size=self.size,
                offset=self.offset,
                narrow=self.narrow,
                full=self.full,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Footer(FastBlocksComponent):
    """Page footer with centered content.

    Thin wrapper over :func:`fastblocks_ui.footer`; emits identical markup.
    """

    content: object = None
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(_footer(content=self.content, class_=self.class_, **self.attrs))


@dataclass
class Hero(FastBlocksComponent):
    """Full-width banner section with title and subtitle.

    Thin wrapper over :func:`fastblocks_ui.hero`; emits identical markup.
    """

    title: object
    subtitle: object | None = None
    variant: Variant | None = None
    size: Size | None = None
    heading_level: HeadingLevel | None = None
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _hero(
                title=self.title,
                subtitle=self.subtitle,
                variant=self.variant,
                size=self.size,
                heading_level=self.heading_level,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Level(FastBlocksComponent):
    """Horizontal layout with left and right sides.

    Thin wrapper over :func:`fastblocks_ui.level`; emits identical markup.
    """

    left: object = None
    right: object = None
    centered: bool = False
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _level(
                left=self.left,
                right=self.right,
                centered=self.centered,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Media(FastBlocksComponent):
    """Image + text media object pattern.

    Thin wrapper over :func:`fastblocks_ui.media`; emits identical markup.
    """

    content: object = None
    image: object = None
    position: str = "start"
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _media(
                content=self.content,
                image=self.image,
                position=self.position,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Section(FastBlocksComponent):
    """Vertical spacing container for page sections.

    Thin wrapper over :func:`fastblocks_ui.section`; emits identical markup.
    """

    content: object = None
    size: Size | None = None
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _section(
                content=self.content, size=self.size, class_=self.class_, **self.attrs
            )
        )


@dataclass
class Shell(FastBlocksComponent):
    """Full-bleed page shell with optional sticky aside column.

    Thin wrapper over :func:`fastblocks_ui.shell`; emits identical markup.
    """

    main: object
    aside: object = None
    aside_width: str | None = None
    max_width: str | None = None
    main_id: str | None = None
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _shell(
                main=self.main,
                aside=self.aside,
                aside_width=self.aside_width,
                max_width=self.max_width,
                main_id=self.main_id,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Tile(FastBlocksComponent):
    """Hierarchical tile for complex nested layouts.

    Thin wrapper over :func:`fastblocks_ui.tile`; emits identical markup.
    """

    content: object = None
    size: str | None = None
    parent: bool = False
    child: bool = False
    ancestor: bool = False
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _tile(
                content=self.content,
                size=self.size,
                parent=self.parent,
                child=self.child,
                ancestor=self.ancestor,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Title(FastBlocksComponent):
    """Typography title element.

    Thin wrapper over :func:`fastblocks_ui.title`; emits identical markup.
    """

    content: object
    size: Size | None = None
    heading_level: HeadingLevel | None = None
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _title(
                content=self.content,
                size=self.size,
                heading_level=self.heading_level,
                class_=self.class_,
                **self.attrs,
            )
        )
