"""UI components.

`Button`, `Field`, `Table` predate WS-16 (hand-written). `Alert`, `Card`,
`Burger`, `Checkbox`, `Dialog`, `Drawer`, `Input`, `Pagination`, `Progress`,
`Switch` are
generated by `scripts/generate_components.py` from fastblocks-ui's manifest
(`fastblocks_htmy/ui/_generated.py` -- do not edit that file by hand).
`Breadcrumb`, `Dropdown`, `Navbar`, `Select`, `Tabs`, `ValidationSummary` are
WS-16 carve-outs (hand-written; see each module's docstring for why).
"""

from __future__ import annotations

from ._generated import (
    Alert,
    Burger,
    Card,
    Checkbox,
    Dialog,
    Drawer,
    Input,
    Pagination,
    Progress,
    Switch,
)
from .breadcrumb import Breadcrumb
from .button import Button
from .dropdown import Dropdown
from .field import Field
from .navbar import Navbar
from .select import Select
from .table import Table
from .tabs import Tabs
from .validation_summary import ValidationSummary

__all__ = [
    "Drawer",
    "Burger",
    "Alert",
    "Breadcrumb",
    "Button",
    "Card",
    "Checkbox",
    "Dialog",
    "Field",
    "Input",
    "Dropdown",
    "Navbar",
    "Pagination",
    "Progress",
    "Select",
    "Switch",
    "Table",
    "Tabs",
    "ValidationSummary",
]
