"""AUTOGENERATED by scripts/generate_components.py -- DO NOT EDIT BY HAND.

Regenerate with:
    python scripts/generate_components.py

Source of truth: fastblocks-ui's manifest.json `params` (itself derived from
the real `fastblocks_ui.helpers` signatures by fastblocks-ui's own
scripts/sync_manifest_params.py). Any manual edit here will be overwritten the
next time this script runs.
"""

from __future__ import annotations

from dataclasses import dataclass
from dataclasses import field as dataclass_field
from typing import Any

from fastblocks_ui import Size, Variant
from fastblocks_ui import (
    alert as _alert,
)
from fastblocks_ui import (
    burger as _burger,
)
from fastblocks_ui import (
    card as _card,
)
from fastblocks_ui import (
    checkbox as _checkbox,
)
from fastblocks_ui import (
    dialog as _dialog,
)
from fastblocks_ui import (
    drawer as _drawer,
)
from fastblocks_ui import (
    input as _input,
)
from fastblocks_ui import (
    pagination as _pagination,
)
from fastblocks_ui import (
    progress as _progress,
)
from fastblocks_ui import (
    switch as _switch,
)
from htmy import Context

from ..base import FastBlocksComponent


@dataclass
class Alert(FastBlocksComponent):
    """Inline notices and status messaging.

    Thin wrapper over :func:`fastblocks_ui.alert`; emits identical markup.
    """

    content: object
    variant: Variant | None = None
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _alert(
                content=self.content,
                variant=self.variant,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Burger(FastBlocksComponent):
    """Burger button that toggles a drawer via the Popover API.

    Thin wrapper over :func:`fastblocks_ui.burger`; emits identical markup.
    """

    controls: str
    label: object = "Menu"
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _burger(
                controls=self.controls,
                label=self.label,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Card(FastBlocksComponent):
    """Content containers and panels.

    Thin wrapper over :func:`fastblocks_ui.card`; emits identical markup.
    """

    header: object | None = None
    body: object | None = None
    footer: object | None = None
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _card(
                header=self.header,
                body=self.body,
                footer=self.footer,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Checkbox(FastBlocksComponent):
    """Checkbox label and control grouping.

    Thin wrapper over :func:`fastblocks_ui.checkbox`; emits identical markup.
    """

    label: object
    checked: bool = False
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _checkbox(
                label=self.label, checked=self.checked, class_=self.class_, **self.attrs
            )
        )


@dataclass
class Dialog(FastBlocksComponent):
    """Native dialog styling and enhancement hooks.

    Thin wrapper over :func:`fastblocks_ui.dialog`; emits identical markup.
    """

    content: object
    id: str
    title: object | None = None
    autoshow: bool = False
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _dialog(
                content=self.content,
                id=self.id,
                title=self.title,
                autoshow=self.autoshow,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Drawer(FastBlocksComponent):
    """Off-canvas panel built on the Popover API.

    Thin wrapper over :func:`fastblocks_ui.drawer`; emits identical markup.
    """

    content: object
    id: str
    label: str | None = None
    side: str = "end"
    tag: str = "div"
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _drawer(
                content=self.content,
                id=self.id,
                label=self.label,
                side=self.side,
                tag=self.tag,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Input(FastBlocksComponent):
    """Native text-like input styling.

    Thin wrapper over :func:`fastblocks_ui.input`; emits identical markup.
    """

    value: object | None = None
    placeholder: object | None = None
    type: str = "text"
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _input(
                value=self.value,
                placeholder=self.placeholder,
                type=self.type,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Pagination(FastBlocksComponent):
    """Pagination links with current page indicator.

    Thin wrapper over :func:`fastblocks_ui.pagination`; emits identical markup.
    """

    current: int
    total: int
    url_pattern: str = "?page={page}"
    siblings: int = 2
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _pagination(
                current=self.current,
                total=self.total,
                url_pattern=self.url_pattern,
                siblings=self.siblings,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Progress(FastBlocksComponent):
    """Progress bar with value and variants.

    Thin wrapper over :func:`fastblocks_ui.progress`; emits identical markup.
    """

    value: int | float
    max_value: int | float = 100
    size: Size | None = None
    variant: Variant = "primary"
    show_label: bool = False
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _progress(
                value=self.value,
                max_value=self.max_value,
                size=self.size,
                variant=self.variant,
                show_label=self.show_label,
                class_=self.class_,
                **self.attrs,
            )
        )


@dataclass
class Switch(FastBlocksComponent):
    """Accessible toggle switch presentation.

    Thin wrapper over :func:`fastblocks_ui.switch`; emits identical markup.
    """

    label: object
    checked: bool = False
    class_: object = None
    attrs: dict[str, Any] = dataclass_field(default_factory=dict)

    def _markup(self, context: Context) -> str:
        return str(
            _switch(
                label=self.label, checked=self.checked, class_=self.class_, **self.attrs
            )
        )
